version: "{build}"

clone_folder: c:\gopath\src\github.com\philippgille\apiomat-sdk-go

# GitHub specific alternative to `clone_depth: <number>`
shallow_clone: true

environment:
  GOPATH: c:\gopath

install:
  - go version
  - go env
  # Get all dependencies
  - go get -d .\...
  # Dependencies in test seem to be excluded from the previous get
  - go get github.com/go-test/deep

build_script:
  - go build github.com\philippgille\apiomat-sdk-go\aomx
  - go build github.com\philippgille\apiomat-sdk-go\aomc

test_script:
  - go test -v github.com\philippgille\apiomat-sdk-go\aomx
  - go test -v github.com\philippgille\apiomat-sdk-go\aomc
