version: "{build}"

clone_folder: c:\gopath\src\github.com\philippgille\apiomat-go

# GitHub specific alternative to `clone_depth: <number>`
shallow_clone: true

environment:
  GOPATH: c:\gopath

install:
  - go version
  - go env

build_script:
  - go build -i github.com\philippgille\apiomat-go\aoms
  - go build -i github.com\philippgille\apiomat-go\aomc
  - go build -i github.com\philippgille\apiomat-go\aom

test_script:
  - go test -v github.com\philippgille\apiomat-go\aoms
  - go test -v github.com\philippgille\apiomat-go\aomc
