git:
  depth: 1

language: go

go:
  - "1.10"

script:
  # builds
  - cd aoms
  - go build
  - cd ../aomc
  - go build
  - cd ../aom
  - go build
  # tests
  - cd ../aoms
  - go test -v
  - cd ../aomc
  - go test -v
