git:
  depth: 1

language: go

go:
  - "1.10"

before_install:
  - go version
  - go env

script:
  # builds
  - go build -i github.com/philippgille/apiomat-go/aoms
  - go build -i github.com/philippgille/apiomat-go/aomc
  - go build -i github.com/philippgille/apiomat-go/aom
  # tests
  - go test -v github.com/philippgille/apiomat-go/aoms
  - go test -v github.com/philippgille/apiomat-go/aomc
