git:
  depth: 1

language: go

go:
  - "1.10"

before_install:
  - go version
  - go env

script:
  # builds
  - go build github.com/philippgille/apiomat-go/aomx
  - go build github.com/philippgille/apiomat-go/aomc
  # Output is needed so that the file and directory names don't clash (both "aom")
  - go build -o aom/aom github.com/philippgille/apiomat-go/aom
  # tests
  - go test -v github.com/philippgille/apiomat-go/aomx
  - go test -v github.com/philippgille/apiomat-go/aomc
